apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: prism-platform-mgmt
  region: us-west-2
  # Add AWS profile
  profile: prism-platform-role

managedNodeGroups:
  - name: al2023-cgroupv2
    amiFamily: AmazonLinux2023
    instanceType: m5.2xlarge  # Upgraded from m5.large to provide more resources
    desiredCapacity: 6
    minSize: 3
    maxSize: 8
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      cgroupVersion: "v2"
      defaultNodeGroup: "true"
    labels:
      cgroup-version: "v2"
      cgroupVersion: "v2"
      defaultNodeGroup: "true"
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        albIngress: true
