apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-manager
  namespace: security-cell-rkfbq-namespace
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m5.2xlarge
