apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-db-service
  namespace: data-cell-w65ql-namespace
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cgroupVersion
                operator: In
                values:
                - v2
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - data
          - weight: 50
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m5.2xlarge
                - m5.4xlarge
