apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-db-service
  namespace: data-cell-w65ql-namespace
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 4
            memory: 8Gi
