apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model-server
  namespace: recommendation-cell-claim-dc75w-namespace
spec:
  replicas: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m5.4xlarge
                - m5.2xlarge
      containers:
      - name: ai-model-server
        resources:
          requests:
            cpu: "1"
            memory: "3Gi"
          limits:
            cpu: "3"
            memory: "6Gi"
