spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - m5.4xlarge
                - m5.2xlarge
          - weight: 50
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - channel
      containers:
      - name: kafka
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
