apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-manager
  namespace: security-cell-rkfbq-namespace
spec:
  template:
    spec:
      containers:
      - name: secrets-manager
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
