global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/REPLACE_WITH_YOUR_WEBHOOK_URL'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
      continue: true
    - match:
        severity: critical
      receiver: 'slack-notifications'
    - match:
        severity: warning
      receiver: 'slack-notifications'
    - match_re:
        service: ^(drift-detector|feedback-loop)$
      receiver: 'team-drift-detection'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#observability-alerts'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        title_link: '{{ template "slack.default.titlelink" . }}'
        footer: 'Prism Platform Alerting'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'https://grafana.example.com/d/drift-detection'

  - name: 'pagerduty-critical'
    pagerduty_configs:
      - routing_key: 'REPLACE_WITH_PAGERDUTY_ROUTING_KEY'
        send_resolved: true
        description: '{{ .CommonAnnotations.summary }}'
        client: 'Alertmanager'
        client_url: '{{ template "pagerduty.default.clientURL" . }}'
        details:
          firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
          resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
          system: 'Prism Platform'

  - name: 'team-drift-detection'
    email_configs:
      - to: 'drift-team@example.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'
