apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler-aws-cluster-autoscaler
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: aws-cluster-autoscaler
        command:
        - ./cluster-autoscaler
        - --cloud-provider=aws
        - --namespace=kube-system
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/prism-platform-mgmt
        - --scale-down-unneeded-time=5m
        - --scale-down-delay-after-add=5m
        - --scale-down-delay-after-delete=5m
        - --scale-down-delay-after-failure=3m
        - --scan-interval=30s
        - --max-node-provision-time=15m
        - --expendable-pods-priority-cutoff=-10
        - --balance-similar-node-groups
        - --skip-nodes-with-local-storage=false
        - --expander=priority
        - --logtostderr=true
        - --stderrthreshold=info
        - --v=4
        env:
        - name: PRIORITY_EXPANDER_CONFIGMAP
          value: cluster-autoscaler-priority-expander
