apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: merbridge
  namespace: istio-system
spec:
  template:
    spec:
      containers:
      - name: merbridge-agent
        command: ["/merbridge"]
        args:
        - "--kind"
