apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpftrace
  namespace: bpftrace
spec:
  selector:
    matchLabels:
      app: bpftrace
  template:
    metadata:
      labels:
        app: bpftrace
    spec:
      containers:
      - name: bpftrace
        image: alpine:3.19
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting bpftrace monitor simulation..."
          while true; do
            echo "BPF trace is running in monitor mode"
            sleep 60
          done
        securityContext:
          privileged: false
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
