apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"prism-platform","cellType":"observability","component":"grafana","managed-by":"crossplane"},"name":"grafana","namespace":"observability-cell-xr5kg-namespace"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"prism-platform","component":"grafana"}},"template":{"metadata":{"labels":{"app":"prism-platform","component":"grafana"}},"spec":{"containers":[{"env":[{"name":"GF_SECURITY_ADMIN_PASSWORD","value":"admin"},{"name":"GF_USERS_ALLOW_SIGN_UP","value":"false"}],"image":"grafana/grafana:9.1.0","name":"grafana","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"8","memory":"32Gi"},"requests":{"cpu":"4","memory":"8Gi"}},"volumeMounts":[{"mountPath":"/var/lib/grafana","name":"grafana-storage"}]}],"volumes":[{"name":"grafana-storage","persistentVolumeClaim":{"claimName":"observability-cell-xr5kg-storage"}}]}}}}'
  creationTimestamp: "2025-03-15T00:42:09Z"
  generation: 1
  labels:
    app: prism-platform
    cellType: observability
    component: grafana
    managed-by: crossplane
  name: grafana
  namespace: observability-cell-xr5kg-namespace
  resourceVersion: "116604"
  uid: 97672846-491f-465b-839b-6127b4280569
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prism-platform
      component: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prism-platform
        component: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        image: grafana/grafana:9.1.0
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: "8Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: observability-cell-xr5kg-storage
status:
  conditions:
  - lastTransitionTime: "2025-03-15T00:42:09Z"
    lastUpdateTime: "2025-03-15T00:42:09Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-03-15T00:52:10Z"
    lastUpdateTime: "2025-03-15T00:52:10Z"
    message: ReplicaSet "grafana-7dc5569dbc" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
