apiVersion: v1
kind: Service
metadata:
  name: data-processor
  namespace: prism-platform
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: data-processor
  ports:
  - port: 8080
    targetPort: 8080
  clusterIP: None
