name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  TF_VERSION: 1.6.0

jobs:
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

  module-validation:
    name: Module Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - crossplane-bootstrap
          - service-mesh
          - ebpf-observability
          - observability-stack
          - cell-deployment
          - cost-estimation
          - telemetry-agent

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Validate Module - ${{ matrix.module }}
      working-directory: modules/${{ matrix.module }}
      run: |
        terraform init -backend=false
        terraform validate
        terraform fmt -check

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        soft_fail: true

  cost-estimation:
    name: Cost Estimation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Generate Infracost diff
      run: |
        infracost diff --path=. \
          --format=comment \
          --show-skipped \
          --out-file=/tmp/infracost.txt || true

    - name: Post Infracost comment
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const path = '/tmp/infracost.txt';
          if (fs.existsSync(path)) {
            const comment = fs.readFileSync(path, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }

  documentation-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check README files
      run: |
        # Check that all modules have README files
        for module in modules/*/; do
          if [ ! -f "${module}README.md" ]; then
            echo "Missing README.md in $module"
            exit 1
          fi
        done
        
        # Check that all examples have README files
        for example in examples/*/; do
          if [ ! -f "${example}README.md" ]; then
            echo "Missing README.md in $example"
            exit 1
          fi
        done
        
        echo "All modules and examples have README files"

    - name: Check for TODO/FIXME
      run: |
        if grep -r "TODO\|FIXME\|XXX" --include="*.tf" --include="*.md" .; then
          echo "Found TODO/FIXME comments that should be resolved"
          exit 1
        fi
        echo "No unresolved TODO/FIXME comments found" 